language: scala
scala:
  - 2.13.1

before_install:
  - "export DISPLAY=:127"
  - "sh -e /etc/init.d/xvfb start"

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coverageReport coveralls